FROM jelastic/maven:3.9.5-openjdk-22.ea-b17 AS build
COPY ./src src
COPY ./pom.xml pom.xml
RUN mvn -f pom.xml clean package -DskipTests

FROM openjdk:22
COPY --from=build ../target/BootcampProj-0.0.1-SNAPSHOT.jar /usr/local/lib/demo.jar
EXPOSE 8084
ENTRYPOINT ["java","-jar","/usr/local/lib/demo.jar"]